server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://192.168.50.137:3306/activity?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    check-process-definitions: false
logging:
  level:
    com.len.mapper: debug
    org.activiti.engine.impl.persistence.entity: trace
